import type { Metadata } from "next";
import { Geist, Geist_Mono, Outfit } from "next/font/google";
import "./globals.css";
import { ReactQueryProvider } from "@/lib/providers/ReactQueryProvider";
import { ReduxProvider } from "@/lib/providers/redux";
import { Toaster } from "sonner";
import AuthInitializer from "@/components/AuthInitializer";
import { SocketBootstrap } from "@/components/SocketBootstrap";
import { RealtimeProvider } from "@/components/RealtimeEventsBootstrap";
import PresenceInitializer from "@/components/PresenceInitializer";
import { AuthGate } from "@/components/AuthGate";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const outFit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${outFit.variable} font-outfit antialiased`}
      >
        <ReduxProvider>
          <ReactQueryProvider>
            <AuthInitializer>
              <SocketBootstrap />
              <PresenceInitializer />
              <RealtimeProvider />
              <AuthGate>{children}</AuthGate>
            </AuthInitializer>
            <Toaster richColors />
          </ReactQueryProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
