import { getEnv } from "../utils/get-env.js";

export interface AppConfig {
  NODE_ENV: "development" | "production" | "test";
  PORT: number;
  DATABASE_URL: string;
  LOG_LEVEL?: string;
  FRONTEND_ORIGIN?: string;
  JWT_SECRET: string;
  AZURE_TENANT_ID: string;
  AZURE_CLIENT_ID: string;
  AZURE_CLIENT_SECRET: string;
  SENDER_EMAIL: string;
  REDIS_HOST: string;
  REDIS_PORT: string;
  REDIS_PASSWORD: string;
  REDIS_TLS: string;
  RATE_LIMIT_GLOBAL_POINTS: string;
  RATE_LIMIT_GLOBAL_DURATION: string;
  RATE_LIMIT_GLOBAL_BLOCK_DURATION: string;
  RATE_LIMIT_LOGIN_POINTS: string;
  RATE_LIMIT_LOGIN_DURATION: string;
  RATE_LIMIT_LOGIN_BLOCK_DURATION: string;
  FAIL_OPEN_ON_REDIS_ERROR: string;
  JWT_ACCESS_EXPIRES_IN: string;
  JWT_REFRESH_EXPIRES_IN_DAYS: string;
  USER_ROLES_TTL_SEC: string;
  PERMISSION_LOOKUP_TTL_SEC: string;
  SUPER_ROLES: string;
  SYSTEM_USER_EMAIL: string;
  SYSTEM_USER_NAME: string;
  SYSTEM_USER_PASSWORD: string;
  SUPER_ROLE_NAME: string;
  SEED_RESOURCES: string;
  REDIS_URL: string;
  STREAM_KEY: string;
  STREAM_DGROUP: string;
  CONSUMER_NAME: string;
  STREAM_DLG: string;
  MAX_RETRY: number;
  WORKFLOW_STREAM:string,
  NOTIFICATION_STREAM: string,
  USE_REDIS:string,

}

const appConfig = (): AppConfig => ({
  NODE_ENV: getEnv("NODE_ENV", "development") as AppConfig["NODE_ENV"],
  PORT: Number(getEnv("PORT")),
  DATABASE_URL: getEnv("DATABASE_URL"),
  LOG_LEVEL: getEnv("LOG_LEVEL", "info"),
  FRONTEND_ORIGIN: getEnv("FRONTEND_ORIGIN"),
  JWT_SECRET: getEnv("JWT_SECRET"),
  AZURE_TENANT_ID: getEnv("AZURE_TENANT_ID"),
  AZURE_CLIENT_ID: getEnv("AZURE_CLIENT_ID"),
  AZURE_CLIENT_SECRET: getEnv("AZURE_CLIENT_SECRET"),
  SENDER_EMAIL: getEnv("SENDER_EMAIL"),
  REDIS_HOST: getEnv("REDIS_HOST"),
  REDIS_PORT: getEnv("REDIS_PORT"),
  REDIS_PASSWORD: getEnv("REDIS_PASSWORD"),
  REDIS_TLS: getEnv("REDIS_TLS"),
  RATE_LIMIT_GLOBAL_POINTS: getEnv("RATE_LIMIT_GLOBAL_POINTS"),
  RATE_LIMIT_GLOBAL_DURATION: getEnv("RATE_LIMIT_GLOBAL_DURATION"),
  RATE_LIMIT_GLOBAL_BLOCK_DURATION: getEnv("RATE_LIMIT_GLOBAL_BLOCK_DURATION"),
  RATE_LIMIT_LOGIN_POINTS: getEnv("RATE_LIMIT_LOGIN_POINTS"),
  RATE_LIMIT_LOGIN_DURATION: getEnv("RATE_LIMIT_LOGIN_DURATION"),
  RATE_LIMIT_LOGIN_BLOCK_DURATION: getEnv("RATE_LIMIT_LOGIN_BLOCK_DURATION"),
  FAIL_OPEN_ON_REDIS_ERROR: getEnv("FAIL_OPEN_ON_REDIS_ERROR"),
  JWT_ACCESS_EXPIRES_IN: getEnv("JWT_ACCESS_EXPIRES_IN"),
  JWT_REFRESH_EXPIRES_IN_DAYS: getEnv("JWT_REFRESH_EXPIRES_IN_DAYS"),
  USER_ROLES_TTL_SEC: getEnv("USER_ROLES_TTL_SEC"),
  PERMISSION_LOOKUP_TTL_SEC: getEnv("PERMISSION_LOOKUP_TTL_SEC"),
  SUPER_ROLES: getEnv("SUPER_ROLES"),
  SYSTEM_USER_EMAIL: getEnv("SYSTEM_USER_EMAIL"),
  SYSTEM_USER_NAME: getEnv("SYSTEM_USER_NAME"),
  SYSTEM_USER_PASSWORD: getEnv("SYSTEM_USER_PASSWORD"),
  SUPER_ROLE_NAME: getEnv("SUPER_ROLE_NAME"),
  SEED_RESOURCES: getEnv("SEED_RESOURCES"),
  REDIS_URL: getEnv("REDIS_URL", "redis://redis:6379"),
  STREAM_KEY: getEnv("STREAM_KEY", "notifications:stream"),
  STREAM_DGROUP: getEnv("STREAM_DGROUP", "notifications:group"),
  STREAM_DLG: getEnv("STREAM_DLG", "notifications:dlq"),
  MAX_RETRY: Number(getEnv("MAX_RETRY")),
  CONSUMER_NAME: getEnv(
    "CONSUMER_NAME",
    `worker-${Math.floor(Math.random() * 9999)}`
  ),
  WORKFLOW_STREAM: getEnv("WORKFLOW_STREAM","workflow_events"),
  NOTIFICATION_STREAM:getEnv( "NOTIFICATION_STREAM", "notification_events"),
  USE_REDIS:getEnv("USE_REDIS")
});

export const config = appConfig();
