import  {getEnv}  from "../utils/get-env";

export interface AppConfig {
  NODE_ENV: "development" | "production" | "test";
  PORT: number;
  LOG_LEVEL?: string;
  FRONTEND_ORIGIN?:string
  JWT_SECRET:string
  AZURE_TENANT_ID: string;
  AZURE_CLIENT_ID: string;
  AZURE_CLIENT_SECRET: string;
  SENDER_EMAIL:string;
  REDIS_HOST:string;
  REDIS_PORT:string;
  REDIS_PASSWORD:string;
  REDIS_TLS:string;
  RATE_LIMIT_GLOBAL_POINTS:string;
  RATE_LIMIT_GLOBAL_DURATION:string;
  RATE_LIMIT_GLOBAL_BLOCK_DURATION:string;
  RATE_LIMIT_LOGIN_POINTS:string;
  RATE_LIMIT_LOGIN_DURATION:string;
  RATE_LIMIT_LOGIN_BLOCK_DURATION:string;
  FAIL_OPEN_ON_REDIS_ERROR:string;
}

const appConfig = (): AppConfig => ({
  NODE_ENV: getEnv("NODE_ENV", "development") as AppConfig["NODE_ENV"],
  PORT: Number(getEnv("PORT")),
  LOG_LEVEL: getEnv("LOG_LEVEL", "info"),
  FRONTEND_ORIGIN:getEnv("FRONTEND_ORIGIN"),
  JWT_SECRET:getEnv("JWT_SECRET"),
  AZURE_TENANT_ID: getEnv("AZURE_TENANT_ID"),
  AZURE_CLIENT_ID: getEnv("AZURE_CLIENT_ID"),
  AZURE_CLIENT_SECRET: getEnv("AZURE_CLIENT_SECRET"),
  SENDER_EMAIL: getEnv("SENDER_EMAIL"),
  REDIS_HOST:getEnv("REDIS_HOST"),
  REDIS_PORT:getEnv("REDIS_PORT"),
  REDIS_PASSWORD:getEnv("REDIS_PASSWORD"),
  REDIS_TLS:getEnv("REDIS_TLS"),
  RATE_LIMIT_GLOBAL_POINTS:getEnv("RATE_LIMIT_GLOBAL_POINTS"),
  RATE_LIMIT_GLOBAL_DURATION:getEnv("RATE_LIMIT_GLOBAL_DURATION"),
  RATE_LIMIT_GLOBAL_BLOCK_DURATION:getEnv("RATE_LIMIT_GLOBAL_BLOCK_DURATION"),
  RATE_LIMIT_LOGIN_POINTS:getEnv("RATE_LIMIT_LOGIN_POINTS"),
  RATE_LIMIT_LOGIN_DURATION:getEnv("RATE_LIMIT_LOGIN_DURATION"),
  RATE_LIMIT_LOGIN_BLOCK_DURATION:getEnv("RATE_LIMIT_LOGIN_BLOCK_DURATION"),
  FAIL_OPEN_ON_REDIS_ERROR:getEnv("FAIL_OPEN_ON_REDIS_ERROR")
});

export const config = appConfig();
