// src/config/http.config.ts
export const HTTPSTATUS = {
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
  NOT_IMPLEMENTED: 501,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504,
} as const;

export type HttpStatusCodeType = typeof HTTPSTATUS[keyof typeof HTTPSTATUS];

export const HttpStatusMessageMap: Record<HttpStatusCodeType, string> = {
  [HTTPSTATUS.OK]: "OK",
  [HTTPSTATUS.CREATED]: "Created",
  [HTTPSTATUS.ACCEPTED]: "Accepted",
  [HTTPSTATUS.NO_CONTENT]: "No Content",
  [HTTPSTATUS.BAD_REQUEST]: "Bad Request",
  [HTTPSTATUS.UNAUTHORIZED]: "Unauthorized",
  [HTTPSTATUS.FORBIDDEN]: "Forbidden",
  [HTTPSTATUS.NOT_FOUND]: "Not Found",
  [HTTPSTATUS.METHOD_NOT_ALLOWED]: "Method Not Allowed",
  [HTTPSTATUS.CONFLICT]: "Conflict",
  [HTTPSTATUS.UNPROCESSABLE_ENTITY]: "Unprocessable Entity",
  [HTTPSTATUS.TOO_MANY_REQUESTS]: "Too Many Requests",
  [HTTPSTATUS.INTERNAL_SERVER_ERROR]: "Internal Server Error",
  [HTTPSTATUS.NOT_IMPLEMENTED]: "Not Implemented",
  [HTTPSTATUS.BAD_GATEWAY]: "Bad Gateway",
  [HTTPSTATUS.SERVICE_UNAVAILABLE]: "Service Unavailable",
  [HTTPSTATUS.GATEWAY_TIMEOUT]: "Gateway Timeout",
};
